mode: "nprint"              # "nprint" o "classic"
output_dir: "./output"

classic:
  mode: all      # Tipo de análisis (paquetes, ventanas, flujos, combinada, all)
  size_of_window: 10     # Número de paquetes por ventana

nprint:
  headers: [ethernet, ipv4, ipv6, absolute_time, icmp, tcp, udp, relative_time, arp]    # Headers de los protocolos incluidos en el output
  masks: [ethernet, arp, ipv4, ipv6, tcp, udp, ip, icmp]                                # Headers de los cuales eliminar información de localización